@portrait Miisan Assets/girl.png
@portrait Eiisan Assets/girl2.png
@portrait Chad Assets/Soilder.png
@Character Assets/characters/feni.char
@Character Assets/characters/npc.char

[start]
Hob(Happy): {shake:1}After a long long journey{/shake} 
Hob(Happy): {shake:1}You've final made it to the final boss of this world{/shake}
Hob: ...
-> What about my sword? [target:end_demo]
-> WTF  [target:end_demo]

[end_demo]
Hob(Happy): {shake:1}Good Luck!{/shake}
Chad: WTF (end)