@portrait Miisan Assets/girl.png
@portrait Eiisan Assets/girl2.png
@portrait Chad Assets/Soilder.png
@Character Assets/characters/feni.char
@Character Assets/characters/npc.char

[start]
Hob(Happy): After a long long journey
Hob(Happy): You've final made it to the final boss of this world
Hob: ...
-> What about my sword? [target:end_demo]
-> WTF  [target:end_demo]

[end_demo]
Hob(Happy): {wave:1}Good Luck!{/wave}
Chad: {color:ffffff}WTF{/color} (end)